FORMAT: 1A
HOST: http://sarahgrace.apiblueprint.org/

# Poupon

Poupon is a simple API allowing consumers to grab data about hip hop.

## Artists Collection [/artists]

### List All Artists [GET]

This will return all of the artist objects in the database.

+ Response 200 (application/json)

        [
            {
                "artist_id":0,
                "name":"Frank Ocean",
                "image":{
                    "height":640,
                    "url":"https://i.scdn.co/image/7db34c8aace6feb91f38601bb75e6b3301b4657a",
                    "width":640
                },
                "genres":[
                    "dance-pop",
                    "indie-r&b",
                    "neo-soul",
                    "pop",
                    "pop-rap",
                    "rap"
                ],
                "albums":[
                    "Blonde",
                    "channel ORANGE (Explicit Version)"
                ],
                "cities":[
                    "New Orleans",
                    "Los Angeles"
                ],
                "related_artists":[
                    "Tyler, The Creator",
                    "Earl Sweatshirt",
                    "Miguel"
                ],
                "external_urls":{
                    "spotify":"https://open.spotify.com/artist/2h93pZq0e7k5yf4dywlkpM"
                }
            },
            {
                "artist_id":1,
                "name":"Kanye West",
                "image":{
                    "height":666,
                    "url":"https://i.scdn.co/image/b86a3dbd77a8353647bff195d310d5eb1bd80af6",
                    "width":999
                },
                "genres":[
                    "pop",
                    "pop-rap",
                    "rap"
                ],
                "albums":[
                    "The Life Of Pablo",
                    "Yeezus",
                    "My Beautiful Dark Twisted Fantasy",
                    "Graduation",
                    "808s & Heartbreak",
                    "Late Registration"
                ],
                "cities":[
                    "Atlanta",
                    "Chicago",
                    "Los Angeles"
                ],
                "related_artists":[
                    "JAY Z",
                    "Kid Cudi",
                    "Drake",
                    "Big Sean"
                ],
                "external_urls":{
                    "spotify":"https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x"
                }
            },
            {
                "artist_id":2,
                "name":"Kendrick Lamar",
                "image":{
                    "height":640,
                    "url":"https://i.scdn.co/image/106c76de27f7e556ebb43947aadd1228862d6cd7",
                    "width":640
                },
                "genres":[
                    "hip-hop",
                    "pop-rap",
                    "rap"
                ],
                "albums":[
                    "DAMN.",
                    "untitled unmastered.",
                    "To Pimp A Butterfly",
                    "good kid, m.A.A.d city",
                    "Section.80",
                    "Overly Dedicated"
                ],
                "cities":[
                    "Compton",
                    "Los Angeles"
                ],
                "related_artists":[
                    "ScHoolboy Q",
                    "Ab-Soul",
                    "A$AP Rocky",
                    "Vince Staples"
                ],
                "external_urls":{
                    "spotify":"https://open.spotify.com/artist/2YZyLoL8N0Wb9xBt1NhZWg"
                }
            }
        ]

### Get Specific Artist [GET /artists/{artist_id}]

This will provide a single artist, given their Artist ID.

+ Parameters
    + artist_id (optional, integer, `1`) ... Artist ID
    
+ Response 200 (application/json)

        {
            "artist_id": 1,
            "name": "Kanye West",
            "genres": [
                {
                    "genre": "rap"
                }, {
                    "genre": "hip hop"
                }
            ],
            "albums": [
                {
                    "album_id": 1,
                }, {
                    "album_id": 2,
                }
            ],
            "image_id" : 1,
            "related_artists": [
                {
                    "artist_id": 2,
                }, {
                    "artist_id": 3,
                }
            ]
        }

            
## Albums Collection [/api/albums]

### List All Albums [GET]

    This will return all of the albums in the database.
+ Response 200 (application/json)

        [
            {
                "album_id": 1,
                "name": "My Beautiful Dark Twisted Fantasy",
                "release_date": "2015-08-05",
                "artists": [
                    {
                        "artist_id": 1,
                    }
                ],
                "tracks": [
                    {
                        "track": "Dark Fantasy",
                    }, {
                        "track": "Gorgeous",
                    }, {
                        "track": "Power",
                    }
                ],
                "cover_art_id": 1,
                "label": "GOOD Music"
            }
        ]

            
## News Collection [/api/news]

### List All Articles [GET]

    This will return all of the news articles in the database.
+ Response 200 (application/json)

        [
            {
                "article_id": 1,
                "published_at": "2015-08-05",
                "title": "Huge new song",
                "score": 23,
                "comments": 5,
                "url": "example.com",
                "artists": [
                    {
                        "artist_id": 2,
                    }, {
                        "artist_id": 4
                    }
                ]
            }
        ]
            
## Cities Collection [/api/cities]

### List All Cities [GET]

    This will return all of the city objects in the database.
    
+ Response 200 (application/json)

        [
            {
                "city_id": "1",
                "name": "Houston",
                "state": "Texas",
                "population": 3219321,
                "published_at": "2015-08-05T08:40:51.620Z",
                "artists": [
                    {
                        "artist_id": 8
                    }, {
                        "artist_id": 15
                    }, {
                        "artist_id": 23
                    }
                ]
            }
        ]