FORMAT: 1A
HOST: http://sarahgrace.apiblueprint.org/

# Poupon

Poupon is a simple API allowing consumers to grab data about hip hop.

## Artists Collection [/api/artists]

### List All Artists [GET]

This will return all of the artist objects in the database.

+ Response 200 (application/json)

        [
            {
                "artist_id": 1,
                "name": "Kanye West",
                "genres": [
                    {
                        "genre": "rap"
                    }, {
                        "genre": "hip hop"
                    }
                ],
                "albums": [
                    {
                        "album_id": 1,
                    }, {
                        "album_id": 2,
                    }
                ],
                "image_id" : 1,
                "related_artists": [
                    {
                        "artist_id": 2,
                    }, {
                        "artist_id": 3,
                    }
                ]
            }
        ]


            
## Albums Collection [/api/albums]

### List All Albums [GET]

    This will return all of the albums in the database.
+ Response 200 (application/json)

        [
            {
                "album_id": 1,
                "name": "My Beautiful Dark Twisted Fantasy",
                "release_date": "2015-08-05",
                "artists": [
                    {
                        "artist_id": 1,
                    }
                ],
                "tracks": [
                    {
                        "track": "Dark Fantasy",
                    }, {
                        "track": "Gorgeous",
                    }, {
                        "track": "Power",
                    }
                ],
                "cover_art_id": 1,
                "label": "GOOD Music"
            }
        ]

            
## News Collection [/api/news]

### List All Articles [GET]

    This will return all of the news articles in the database.
+ Response 200 (application/json)

        [
            {
                "article_id": 1,
                "published_at": "2015-08-05",
                "title": "Huge new song",
                "score": 23,
                "comments": 5,
                "url": "example.com",
                "artists": [
                    {
                        "artist_id": 2,
                    }, {
                        "artist_id": 4
                    }
                ]
            }
        ]
            
## Cities Collection [/api/cities]

### List All Cities [GET]

    This will return all of the city objects in the database.
    
+ Response 200 (application/json)

        [
            {
                "city_id": "1",
                "name": "Houston",
                "state": "Texas",
                "population": 3219321,
                "published_at": "2015-08-05T08:40:51.620Z",
                "artists": [
                    {
                        "artist_id": 8
                    }, {
                        "artist_id": 15
                    }, {
                        "artist_id": 23
                    }
                ]
            }
        ]