runtime: python
env: flex
service: default
runtime_config:
  python_version: 3.6
entrypoint: gunicorn -b :$PORT main:app

api_version: 2
threadsafe: true
skip_files:
- ^poupon-web/node_modules/*?
- ^.git/*?

env_variables:
    SQLALCHEMY_DATABASE_URI: >-
      postgresql+psycopg2://postgres:downing@/postgres?host=/cloudsql/poupon-181003:us-central1:db-clone

beta_settings:
    cloud_sql_instances: poupon-181003:us-central1:db-test

handlers:
- url: /.*
  script: main.app
