runtime: python27
api_version: 1
threadsafe: true
skip_files:
- ^poupon-web/node_modules/*?
- ^.git/*?

handlers:
- url: /api/.*
  script: main.app

- url: /
  static_files: poupon-web/build/index.html
  upload: poupon-web/build/index.html

- url: /(.*\.(.*))
  static_files: poupon-web/build/\1
  upload: poupon-web/build/(.*)

- url: /(.*)
  static_files: poupon-web/build/index.html
  upload: poupon-web/build/index.html
