runtime: python
env: flex
runtime_config:
  python_version: 3.6
entrypoint: gunicorn -b :$PORT main:app

api_version: 1
threadsafe: true
skip_files:
- ^poupon-web/node_modules/*?
- ^.git/*?

env_variables:
    SQLALCHEMY_DATABASE_URI: >-
      postgresql+psycopg2://postgres:downing@/postgres?host=/cloudsql/poupon-181003:us-central1:db-test

beta_settings:
    cloud_sql_instances: poupon-181003:us-central1:db-test

handlers:
- url: /
  static_files: poupon-web/build/index.html
  upload: poupon-web/build/index.html

- url: /api/.*
  script: main.app

- url: /(.*\.(.*))
  static_files: poupon-web/build/\1
  upload: poupon-web/build/(.*)  

- url: /(.*)
  static_files: poupon-web/build/index.html
  upload: poupon-web/build/index.html
